spring:
  application:
    name: order-svc
  profiles:
    active: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/acm
    username: acm
    password: Qwerty123!
  flyway:
    enabled: true
  jpa:
    open-in-view: false

order:
  adapters:
    product: mock
    inventory: mock
    payment: mock
    logistics: mock
