plugins {
    id 'base'
}

allprojects {
    group = 'org.acm'
    version = '0.0.1-SNAPSHOT'
}

subprojects {
		pluginManager.withPlugin('io.spring.dependency-management') {
			dependencyManagement {
				imports {
					mavenBom "org.springframework.cloud:spring-cloud-dependencies:2025.1.3"
					mavenBom "io.github.resilience4j:resilience4j-bom:2.4.0"
				}
			}
		}

	pluginManager.withPlugin('org.springframework.boot') {
        tasks.named('bootBuildImage') {
            imageName = "acm/${project.name}:${project.version}"
            tags = ["acm/${project.name}:latest"]
            environment = ["BP_JVM_VERSION": "17"]
            builder = "docker.m.daocloud.io/paketobuildpacks/builder-noble-java-tiny:latest"
            // run image 版本须与 builder 元数据中的 stack runImage 一致
            runImage = "docker.m.daocloud.io/paketobuildpacks/ubuntu-noble-run-tiny:0.0.122"
        }
    }

    pluginManager.withPlugin('java') {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(17)
            }
        }

        tasks.named('test') {
            useJUnitPlatform()
        }
    }
}
