plugins {
    id 'base'
}

allprojects {
    group = 'org.acm'
    version = '0.0.1-SNAPSHOT'
}

subprojects {
    pluginManager.withPlugin('java') {
        java {
            toolchain {
                languageVersion = JavaLanguageVersion.of(17)
            }
        }

        tasks.named('test') {
            useJUnitPlatform()
        }
    }
}
