pluginManagement {
    repositories {
        //国内镜像
        maven { url = "https://maven.aliyun.com/repository/central" }
        maven { url = "https://maven.aliyun.com/repository/public" }
        maven { url = "https://maven.aliyun.com/repository/gradle-plugin" }
        //官方仓库
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id 'org.springframework.boot' version '4.1.1'
        id 'io.spring.dependency-management' version '1.1.7'
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'acm-ai-integration'

include 'customer-agent'
include 'customer-svc'
include 'order-svc'
include 'kb-svc'

include 'common-lib'
